name: Build image & Deploy

on:
  push:
    branches: [ "main" ]

jobs:

  # Maybe add a build job here to bulid and test the code before building the docker file! 

  docker:
      # needs: build
      name: Build and Push Docker Image
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm install
      
      - name: Run tests
        run: npm run test
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ticketmastergang/ticketmaster:frontend

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile.prod
          push: true
          tags: ticketmastergang/ticketmaster:frontend
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
        needs: docker
        name: Deploy on cloud server
        runs-on: self-hosted
        steps:
          - name: Checkout code
            uses: actions/checkout@v2
          - name: Deploy
            env:
              S3_URL: ${{ vars.S3_URL }}
            run: |
              docker-compose pull
              docker-compose up -d

